#!/usr/bin/env python3
"""复刻 #3: Building Effective Agents — 5 种工作流模式。"""

from diagram_renderer import Diagram, Node

# ── 1. Prompt Chaining ──────────────────────────────────────────
d = Diagram("Workflow: Prompt Chaining", "串行分解 → 逐步执行", width=860, height=300)
d.add_node(Node("in",  "输入",          "input",   tag="IN",  row=0, col=0))
d.add_node(Node("s1",  "Step 1",        "backend", tag="S1",  row=0, col=1, sublabel="分解任务"))
d.add_node(Node("s2",  "Step 2",        "backend", tag="S2",  row=0, col=2, sublabel="执行子任务"))
d.add_node(Node("s3",  "Step 3",        "backend", tag="S3",  row=0, col=3, sublabel="聚合结果"))
d.add_node(Node("out", "输出",          "focal",   tag="OUT", row=0, col=4))
d.auto_layout(gap_x=30, node_width=120, node_height=48)
d.add_edge("in", "s1", "触发",  "default")
d.add_edge("s1", "s2", "传递",  "default")
d.add_edge("s2", "s3", "传递",  "default")
d.add_edge("s3", "out","输出",  "accent")
d.save("recreate-workflow-chaining.html")
print("✓ recreate-workflow-chaining.html")

# ── 2. Routing ──────────────────────────────────────────────────
d = Diagram("Workflow: Routing", "按输入分类 → 路由到专用处理器", width=860, height=360)
d.add_node(Node("in",  "输入",          "input",   tag="IN",  row=0, col=1))
d.add_node(Node("clf", "分类器",        "focal",   tag="CLF", row=1, col=1, shape="diamond"))
d.add_node(Node("h1",  "处理器 A",      "backend", tag="P1",  row=2, col=0))
d.add_node(Node("h2",  "处理器 B",      "backend", tag="P2",  row=2, col=1))
d.add_node(Node("h3",  "处理器 C",      "backend", tag="P3",  row=2, col=2))
d.add_node(Node("out", "输出",          "store",   tag="OUT", row=3, col=1))
d.auto_layout(gap_x=30, gap_y=30, node_width=120, node_height=48)
d.add_edge("in",  "clf","提交",  "default")
d.add_edge("clf", "h1", "路由 A", "link")
d.add_edge("clf", "h2", "路由 B", "accent")
d.add_edge("clf", "h3", "路由 C", "link")
d.add_edge("h1",  "out","回写",  "dashed")
d.add_edge("h2",  "out","回写",  "dashed")
d.add_edge("h3",  "out","回写",  "dashed")
d.save("recreate-workflow-routing.html")
print("✓ recreate-workflow-routing.html")

# ── 3. Parallelization ──────────────────────────────────────────
d = Diagram("Workflow: Parallelization", "并行执行 → 同步聚合", width=860, height=360)
d.add_node(Node("in",  "输入",          "input",   tag="IN",  row=0, col=1))
d.add_node(Node("sp",  "分发器",        "focal",   tag="FAN", row=1, col=1))
d.add_node(Node("w1",  "Worker 1",      "backend", tag="W1",  row=2, col=0))
d.add_node(Node("w2",  "Worker 2",      "backend", tag="W2",  row=2, col=1))
d.add_node(Node("w3",  "Worker 3",      "backend", tag="W3",  row=2, col=2))
d.add_node(Node("ag",  "聚合器",        "backend", tag="AGG", row=3, col=1))
d.add_node(Node("out", "输出",          "store",   tag="OUT", row=4, col=1))
d.auto_layout(gap_x=30, gap_y=24, node_width=120, node_height=44)
d.add_edge("in",  "sp", "提交",  "default")
d.add_edge("sp",  "w1", "并行",  "accent")
d.add_edge("sp",  "w2", "并行",  "accent")
d.add_edge("sp",  "w3", "并行",  "accent")
d.add_edge("w1",  "ag", "回传",  "default")
d.add_edge("w2",  "ag", "回传",  "default")
d.add_edge("w3",  "ag", "回传",  "default")
d.add_edge("ag",  "out","合并",  "accent")
d.save("recreate-workflow-parallel.html")
print("✓ recreate-workflow-parallel.html")

# ── 4. Orchestrator-Workers ─────────────────────────────────────
d = Diagram("Workflow: Orchestrator-Workers", "主代理编排 → 子代理执行", width=860, height=360)
d.add_node(Node("in",  "输入",          "input",   tag="IN",  row=0, col=1))
d.add_node(Node("orc", "编排器",        "focal",   tag="ORT", row=1, col=1, sublabel="分配 · 调度 · 聚合"))
d.add_node(Node("wk1", "Worker A",      "backend", tag="WA",  row=2, col=0, sublabel="子任务 1"))
d.add_node(Node("wk2", "Worker B",      "backend", tag="WB",  row=2, col=1, sublabel="子任务 2"))
d.add_node(Node("wk3", "Worker C",      "backend", tag="WC",  row=2, col=2, sublabel="子任务 3"))
d.add_node(Node("syn", "综合输出",      "store",   tag="OUT", row=3, col=1))
d.auto_layout(gap_x=30, gap_y=30, node_width=130, node_height=48)
d.add_edge("in",  "orc","任务",  "accent")
d.add_edge("orc", "wk1","委派",  "default")
d.add_edge("orc", "wk2","委派",  "default")
d.add_edge("orc", "wk3","委派",  "default")
d.add_edge("wk1", "orc","汇报",  "dashed")
d.add_edge("wk2", "orc","汇报",  "dashed")
d.add_edge("wk3", "orc","汇报",  "dashed")
d.add_edge("orc", "syn","合成",  "accent")
d.save("recreate-workflow-orchestrator.html")
print("✓ recreate-workflow-orchestrator.html")

# ── 5. Evaluator-Optimizer ──────────────────────────────────────
d = Diagram("Workflow: Evaluator-Optimizer", "生成 → 评估 → 迭代优化", width=860, height=360)
d.add_node(Node("in",  "输入/需求",     "input",   tag="IN",  row=0, col=1))
d.add_node(Node("gen", "生成器",        "backend", tag="GEN", row=1, col=0, sublabel="LLM 生成"))
d.add_node(Node("jud", "评估器",        "focal",   tag="JUD", row=1, col=2, sublabel="评分 · 反馈"))
d.add_node(Node("out", "达标输出",      "store",   tag="OUT", row=2, col=1))
d.add_node(Node("loop","反馈循环",      "external",tag="↻",   row=2, col=0, shape="diamond"))
d.auto_layout(gap_x=40, gap_y=30, node_width=130, node_height=48)
d.add_edge("in",  "gen","需求",  "default")
d.add_edge("gen", "jud","提交",  "default")
d.add_edge("jud", "out","通过",  "accent")
d.add_edge("jud", "loop","不通过", "link")
d.add_edge("loop","gen","重试",  "dashed")
d.save("recreate-workflow-evaluator.html")
print("✓ recreate-workflow-evaluator.html")
